#
# SystemMock solution
# AppVeyor configuration
#

version: 0.1.0.{build}

branches:
  only:
    - master
    - production
  except:
    - gh-pages

os: Windows Server 2012

platform: Any CPU
configuration: Debug

build:
  project: SystemMock.sln
  verbosity: detailed

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1.0.{build}"
  assembly_file_version: "1.0.0.0"
  assembly_informational_version: "{version}"

test:
  assemblies:
    - SystemMock.Tests.dll
