#
# SystemMock solution
# AppVeyor configuration
#

version: 0.3.1.{build}

branches:
  except:
    - gh-pages

os: Windows Server 2012

platform: Any CPU
configuration: Debug

build:
  project: SystemMock.sln
  verbosity: detailed

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

test:
  assemblies:
    - SystemMock.Tests.dll

cache:
  - packages